### ISSUE TITLE
tables scanning for orderedness when they shouldn't be

### ISSUE THREAD

**Issue by tpoterba** [hail-is/hail#3492]
example:

```
In [10]: hl.utils.range_table(1).select(x=[1])
2018-05-02 23:41:10 Hail: INFO: Coerced sorted dataset
Out[10]: <hail.table.Table at 0x108dffcc0>
```
Note that if you annotate `x=1`, it doesn't scan (this is related to broadcasts or something)

**Comment by jigold** [comment]
Was this fixed by #3493 ?

**Comment by tpoterba** [comment]
no. That fixed the intrusion of this bug into the Expression.take/show/collect stuff, but it's still a problem.

**Comment by patrick-schultz** [comment]
I think I've fixed this, will PR soon.

**Comment by jigold** [comment]
@patrick-schultz Is the bug from this warning?

```
[ant:scalac] /Users/jigold/hail/src/main/scala/is/hail/table/Table.scala:584: warning: comparing values of types Array[String] and Int using `==' will always yield false
[ant:scalac]               ordered.typ.partitionKey == partitionKeys.length) {
```

**Comment by patrick-schultz** [comment]
Yeah, that was it!

**Comment by jigold** [comment]
@patrick-schultz  Do you want me to make a PR?

**Comment by patrick-schultz** [comment]
Sorry, I have the change in a PR that also makes TableRange produce an OrderedRVD (which I at first thought was causing this problem). It'll go up in a minute.
